# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title ass
#' @description This function for some given integer n generates all possible 0-1 assignment vectors of 2n survey participants in such a way that exactly n of them are assigned to group 0 (control) and the other n ones are assigned to group 1 (treatment).
#' 
#' @param n - a numeric value. Due to contrains n can't be larger than 30. 
#' @return A matrix with 2n columns and an appropriate number of rows. 
#' 
#' @export
ass <- function(n) {
    .Call('andzinskihw6_ass', PACKAGE = 'andzinskihw6', n)
}

#' @title mode
#' @description This function determines the most frequently occurring value in an integer vector (mode).
#' 
#' @param x - a numeric vector
#' @return Value that occurs most frequently in given numeric vector x. NA elements are ignored, if given vector x contains only NA elements then NA value will be returned.
#' 
#' @export
mode <- function(x) {
    .Call('andzinskihw6_mode', PACKAGE = 'andzinskihw6', x)
}

#' @title simplify2array
#' @description This function tries to convert list to matrix or numeric vector.
#' 
#' @param x - a list
#' @return A matrix, numeric vector or a list. If it is feasible to simplify (all elements of given x list are numeric vectors of the same length) then matrix or numeric vector is returned. Otherwise function returns unchanged given list x.
#' 
#' @export
simplify2array <- function(x) {
    .Call('andzinskihw6_simplify2array', PACKAGE = 'andzinskihw6', x)
}

